# Use Node 20 base image
FROM node:20

# Create app directory inside container
WORKDIR /app

# Copy only package files first (for faster rebuilds)
COPY strapi-app/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the Strapi project code
COPY strapi-app/. .

# Set environment to production
ENV NODE_ENV=production

# Build Strapi admin panel
RUN npm run build

# Expose Strapi default port
EXPOSE 1337

# Start Strapi
CMD ["npm", "start"]
